name: ci

on:
  push: 

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies (clean install)
        run: npm ci
      
      - name: Check syntax
        run: node --check server.js
      
      - name: Run Markdown lint
        run: npm run lint:md

      - name: Package application
        working-directory: app
        run: zip -r ../app.zip .

      - name: Upload application artifact
        uses: actions/upload-artifact@v4
        with:
          name: application
          path: app.zip