name: ci

on:
  push: 

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: set up nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: install dependencies (clean install)
        run: npm ci
      
      - name: check syntax
        run: node --check server.js
      
      - name: run Markdown lint
        run: npm run lint:md